### ISSUE TITLE
07: As a user, I can utilize the unlocked banners/icons to customise my profile.(Customization in general)

### ISSUE THREAD

**Issue by LooPyt** [sopra-fs24-group-08/sopra-fs24-group-08-server#7]
- [ ] sopra-fs24-group-08/sopra-fs24-group-08-server#71
- [ ] sopra-fs24-group-08/sopra-fs24-group-08-client#13

**Comment by Davtan00** [comment]
0b0586608c4aa1943a32378f73da77c6d1e0ccb3, 0f3bf7a4fbce952128f372f7d1c2c20de429b97f,e4b1c7f5dc3fb99fdd4a1c39096462ebe0598a57  Wasn't committing often enough so , several issues were covered as good as possible but it's all stuffed in here.
